### ISSUE TITLE
您好，在最新版中没有找到xray

### ISSUE THREAD

**Issue by BrunuhVille** [aorosora/NEWIFI-D2-LEDE#1]
2020.12.2最新版，在 服务->SSRplus 和 VPN->v2ray服务器 中仔细点了各个下拉菜单选项
并没有看到xray或者xtls
想问一下XRay是在哪里
谢谢

**Comment by aorosora** [comment]
没有吗，我记得有加啊，抱歉可能得等到我晚上下班后才能再编译一份。

**Comment by aorosora** [comment]
[试试这个。](https://github.com/aorosora/NEWIFI-D2-LEDE/releases/tag/2020.12.19)
![image](https://user-images.githubusercontent.com/24385425/102634744-3debf480-418d-11eb-9c67-88dc987cf685.png)
