### ISSUE TITLE
u盘挂载问题

### ISSUE THREAD

**Issue by SanKanochi** [aorosora/NEWIFI-D2-LEDE#2]
作者你好，我在挂载点里总是找不到插入的u盘。使用的是移动硬盘，ext4格式的。然后在/dev里面也找不到有挂载点。能请问一下可能是什么原因吗

**Comment by aorosora** [comment]
试试这个固件：[2020.12.20](https://github.com/aorosora/NEWIFI-D2-LEDE/releases/tag/2020.12.20)

**Comment by SanKanochi** [comment]
还是挂载不了，我的移动硬盘应该是usb3.0.我试了一下别的固件，发现是能检测到的
![Snipaste_2020-12-20_01-18-58](https://user-images.githubusercontent.com/66832261/102695367-c63bc980-4261-11eb-929e-c96882137ab2.jpg)
![Snipaste_2020-12-20_01-10-32](https://user-images.githubusercontent.com/66832261/102695371-c936ba00-4261-11eb-81c1-56ea1fe87d9a.jpg)

**Comment by aorosora** [comment]
我测试了USB2.0/3.0都可以啊，你重启一下或者重置一下试试？ ![图片](https://user-images.githubusercontent.com/24385425/102695671-c0df7e80-4263-11eb-95a8-f2148ab2cf0f.png)
用cfdisk看看能不能识别出来
![图片](https://user-images.githubusercontent.com/24385425/102695709-013efc80-4264-11eb-9b06-acd93d2eb3eb.png)

**Comment by SanKanochi** [comment]
我刷回去试了，发现是可以用的，之前可能是配置有点问题了。谢谢作者答疑
