### ISSUE TITLE
大佬，netdata能否安排一下

### ISSUE THREAD

**Issue by BrunuhVille** [aorosora/NEWIFI-D2-LEDE#3]
luci-app-netdata
https://github.com/openwrt/packages/tree/master/admin/netdata
https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-netdata
图形化实时监控

**Comment by aorosora** [comment]
https://github.com/aorosora/NEWIFI-D2-LEDE/releases/tag/2020.1.2.1
