### ISSUE TITLE
有个疑问，为什么选择了ssrplus而不是passwall

### ISSUE THREAD

**Issue by BrunuhVille** [aorosora/NEWIFI-D2-LEDE#4]
ssrplus和passwall存在什么差异吗，有点好奇

**Comment by aorosora** [comment]
主要还是我自己用的这个固件，因为找不到别人的跟着V2Ray版本走的固件，用新版的配置受限很大才自己编译的，passwall我倒是有编译一个在电脑上开虚拟机做旁路由用一次，感觉好像比ssrplus多了个负载均衡，好像passwall还能单独指定Netflix的线路，passwall个人感觉可操作性更高级一点吧，但我是自己搭的代理，就两条线路，一台是平常用的，一台是备用的，没有这些方面的需求。所以就选了选项配置简单点的ssrplus。

**Comment by aorosora** [comment]
openclash本来我也打算加进去的，还自带一个DNS加密的功能，但是新三那闪存。。。一言难尽
